### ISSUE TITLE
Theming support

### ISSUE THREAD

**Issue by techquestions** [Sharcoux/rn-css#11]
Are there any plans to add theming, similar to [how styled-components is doing it](https://styled-components.com/docs/advanced#theming)?

**Comment by Sharcoux** [comment]
Hum. Good point... I'd rather provide sth more general to pass on values to the components. The issue might be about typing... I need to think about it.

**Comment by techquestions** [comment]
@Sharcoux please let me know once you have some ideas in mind. I could also propose something I you want.

**Comment by Sharcoux** [comment]
Well, the idea is to have a context provider that passes its data to all styled components. This part is obvious.

Now, what I would like is to create a SharedDataProvider or sth like that, instead of a theme provider. The idea is that we can use it to share any kind of data with the components.

The implementation seems straight forward, but I don't know how to type this... Should I just use `unknown` and let the user cast the data?

**Comment by Sharcoux** [comment]
@techquestions  Done. Please try version 1.3.0-0 and report if you notice anything wrong. I didn't have time to test correctly.

**Comment by FloValence** [comment]
Hello, when will it be available on NPM? It prevents me from trying the solution.

**Comment by Sharcoux** [comment]
Sorry, I missed your reply, but 1.3.0-0 was normally available on NPM. Anyway, now you can use the version `1.3.1`. Sorry for the delay in answer.

Don't hesitate to reopen if you encounter an issue with the new solution, and thanks for the feedback!
