### ISSUE TITLE
Media Query 

### ISSUE THREAD

**Issue by fera765** [Sharcoux/rn-css#4]
For @media implementation would you use the use Window dimensions, to get the height and width of the screen?

I tried to make an implementation but I was not successful kkkkk, because there would have to be 2 verification of the hover and the media

**Comment by Sharcoux** [comment]
Yes, the code need to be changed a bit so that the style within hover get treated exactly the same as the normal style, including the parsing of media queries. I think that I know more or less how to add support for media query and for transitions. I just don't have time to take care of it right now unfortunately. If it can wait like a month, I'll do it by then I think.

**Comment by fera765** [comment]
Fantastic, I'm enjoying working with your lib ..
![Screenshot_20200804-084108](https://user-images.githubusercontent.com/35400150/89289826-41dc0780-d62e-11ea-940c-e94cce974dc7.png)

**Comment by joseDaKing** [comment]
Hi, great library just so you know there are media query parser library.
link: https://www.npmjs.com/package/css-mediaquery

The library contains typings also you can find them here.
link: https://www.npmjs.com/package/@types/css-mediaquery

**Comment by Sharcoux** [comment]
@fera765 @joseDaKing , A first version of rn-css with Media Query is in pre-release (version 1.0.0-1). If you want to try it, you are welcome to raise any bug you might encounter.
